dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
services:
  - docker

install:
  - pipenv install --dev

jobs:
  include:
    - stage: "Unit Tests"
      script:
        - PYTHONPATH=./src pipenv run pytest test/unit/
    - stage: "Build"
      script:
        - docker build . -t currency_converter:latest
    - stage: "Integration Tests"
      script:
        - docker run -p 8000:8000 currency_converter:latest
        - PYTHONPATH=./test/integration pipenv run robot --outputdir out test/integration/
